name: ecma_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.6
  image: ^4.0.17
  path_provider: ^2.1.5
  cloud_firestore: ^5.5.1
  firebase_core: ^3.8.1
  firebase_storage: ^12.3.7
  file_picker: ^6.1.1
  google_sign_in: ^6.2.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  google_generative_ai: ^0.2.1
  image_picker: ^1.0.7
  pdf: ^3.10.7
  printing: ^5.12.0
  barcode: ^2.2.4
  firebase_auth: ^5.3.4
  shared_preferences: ^2.2.2
  device_info_plus: ^9.1.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/ecmalogo.png
    - assets/icons/pencil.svg
    - assets/icons/no_erasures.svg
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Poppins-Black.ttf
          weight: 900
        - asset: fonts/Poppins-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ThinItalic.ttf
          style: italic
          weight: 100
